
jslave:
  build: .
  # image: dockerjenkinsswarmslave_jslave
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/bin/docker
    # - /var/lib/docker:/var/lib/docker
    - ./home/jenkmaster-creds:/etc/jenkmaster-creds
    - ../sirjenkins/ci:/ci
    - ~/.docker/config.json:/var/jenkins_home/.docker/config.json
    # - ~/.ssh:/var/jenkins_home/.ssh
  environment:
    # - 'SWARM_MASTER=http://sirjenkins:8080'
    - 'EXECUTORS=1'
    - 'SWARM_LABELS=docker sbt'
  external_links:
    - sirjenkins_sirjenkins_1
  privileged: true
