---


version: '3'
services:
  swarm:
    depends_on: ['dind']
    build: swarm-agent
    environment:
      - SWARM_LABELS=docker dind
      - LOGLEVEL=DEBUG
    # external_links:
    #   - jenkins
    volumes:
      - ./.credentials:/etc/swarm/credentials
      - jenkins:/home/jenkins
      - varrun:/var/run
  dind:
    image: docker:17.03.1-ce-dind
    volumes:
      - jenkins:/home/jenkins
      - varrun:/var/run
    privileged: true

volumes:
  varrun: {}
  jenkins: {}
